# Configuración adicional para compilación optimizada

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
linker = "i686-linux-android21-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"

# Optimizaciones para release
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

# Optimizaciones específicas para tamaño (útil para WebAssembly)
[profile.release-small]
inherits = "release"
opt-level = "s"
strip = true